//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinkLady.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PinkLady.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   赤|R青
        ///R赤
        ///青|R緑
        ///R青
        ///--
        ///R青|赤
        ///--
        ///緑
        ///R緑
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   青
        ///R青
        ///R赤|R青
        ///R青
        ///R青
        ///--
        ///青|R青
        ///--
        ///R赤|R青
        ///R赤|R青
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   R赤
        ///青|R青
        ///緑
        ///R緑
        ///R青
        ///--
        ///R赤|青
        ///R赤
        ///R赤
        ///R青
        ///R緑
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   R赤
        ///緑|青|赤|青
        ///青|R青
        ///R緑|R青
        ///--
        ///青|青
        ///R緑|R青
        ///赤|青|赤|青
        ///R赤|R緑|R緑
        ///R緑|緑
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   R赤|R赤
        ///R赤
        ///赤|緑|青
        ///R赤|R青
        ///--
        ///R赤|R青
        ///--
        ///緑|緑|赤|赤|青|青
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   緑
        ///緑|緑
        ///R緑|R赤|R青|R緑
        ///青|青|青|R緑|青|R緑|青
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("_6", resourceCulture);
            }
        }
    }
}
